config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :usuarios, controllers: {
    registrations: 'usuario/registrations',
    sessions: 'usuario/sessions',
    passwords: 'usuario/passwords',
    omniauth_callbacks: 'usuario/omniauth_callbacks'
  }

  # API
  namespace :api do
    devise_scope :usuario do
      match 'usuarios/sign_in', to: '/usuario/sessions#create', via: [:post]
      match 'usuarios/sign_out', to: '/usuario/sessions#destroy', via: [:delete]
      match 'usuarios/validate_token',
            to: '/usuario/sessions#validate_token',
            via: [:get]
      match 'usuarios', to: '/usuario/registrations#create', via: [:post]
      match 'usuarios', to: '/usuario/registrations#update', via: [:patch, :put]
      match 'usuarios/password', to: '/usuario/passwords#create', via: [:post]
      match 'usuarios/auth/facebook/validate_token',
            to: '/usuario/omniauth_callbacks#validate_facebook_token',
            via: [:get, :post]
      match 'usuarios/auth/google_oauth2/validate_token',
            to: '/usuario/omniauth_callbacks#validate_google_token',
            via: [:get, :post]
    end
    resources :lojas, only: [:index, :show, :create, :update],
                      param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :pistas, only: [:index, :show, :create, :update],
                       param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :eventos, only: [:index, :show, :create, :update],
                        param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :esportes, only: [:index], defaults: { format: 'json' }
  end

  # CADASTRO
  namespace :cadastros do
    resources :lojas, param: :uuid
    resources :eventos, param: :uuid
    resources :pistas, param: :uuid
    resources :campeonatos, param: :uuid do
      post :evento, on: :member, to: 'campeonatos#create_evento'
      scope module: 'campeonatos' do
        resources :participantes, param: :uuid do
          post :allocate, on: :collection
        end
        resources :etapas, param: :uuid do
          post :generate, on: :collection
        end
      end
    end
  end

  # AUTOCOMPLETE
  resources :esportes, only: [] do
    get :autocomplete_esporte_nome, on: :collection
  end
  resources :locais, only: [] do
    get :autocomplete_cidade_nome, on: :collection
  end

  # PESQUISA
  resources :lojas, only: [:index, :show], param: :uuid
  resources :campeonatos, only: [:index, :show], param: :uuid
  resources :eventos, only: [:index, :show], param: :uuid
  resources :pistas, only: [:index, :show], param: :uuid

  resources :contacts, only: [:index, :create]

  match 'index', to: 'home#index', via: [:get]
  match 'contact', to: 'contacts#index', via: [:get]
  match 'about', to: 'home#about', via: [:get]
  match 'cadastros', to: 'home#cadastros', via: [:get]

  # ERRORS
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/loja.rb
class Loja < ApplicationRecord
  belongs_to :responsavel, class_name: 'Usuario'

  has_many :locais, as: :localizavel, dependent: :destroy
  accepts_nested_attributes_for :locais, allow_destroy: true

  has_one :horario, as: :funcionamento, dependent: :destroy
  accepts_nested_attributes_for :horario, allow_destroy: true

  has_and_belongs_to_many :esportes
  has_and_belongs_to_many :eventos

  has_attached_file :logo,
                    styles: {
                      small: '340x200>',
                      original: '800x600>'
                    }

  is_impressionable

  before_create :set_uuid

  def to_param
    uuid
  end

  validates :nome, presence: true, length: { maximum: 50 }
  validates :descricao, presence: true, length: { maximum: 500 }
  validates :telefone, length: { maximum: 20 }
  validates :email, length: { maximum: 50 }, allow_blank: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :website, length: { maximum: 150 }
  validates :facebook, length: { maximum: 150 }
  validates :locais, presence: true
  validates_associated :locais
  validates :esportes, presence: true
  validates :responsavel, presence: true
  validates_attachment :logo,
                       size: { in: 0..5.megabytes },
                       content_type: { content_type: /^image\/(jpeg|png)$/ }

  scope :find_like_name, ->(nome) {
    where('lojas.nome LIKE ?', "#{nome}%") if nome.present?
  }

  scope :find_by_estado, ->(estado) {
    joins(:locais).where('locais.estado = ?', estado) if estado.present?
  }

  scope :find_by_esporte_categoria, ->(categoria) {
    joins(:esportes).where(esportes: { categoria: categoria })
                    .distinct if categoria.present?
  }

  def contato
    contato = telefone
    contato += ' / ' if contato.present?
    contato += email
    return contato
  end

  def logo_url
    logo.url(:original).sub(/\?\d+$/, '') if logo.exists?
  end

  def responsavel_uuid
    responsavel.uuid
  end

  def as_json(options={})
    super(only: [:nome, :descricao, :telefone, :email, :website, :facebook,
                 :uuid],
          methods: [:logo_url, :responsavel_uuid],
          include: {
            locais: { except: [:id, :localizavel_id, :localizavel_type,
                               :created_at, :updated_at] },
            esportes: { except: [:created_at, :updated_at] },
            horario: { except: [:id, :funcionamento_id, :funcionamento_type,
                                :created_at, :updated_at] }
          }
    )
  end

  def share_message
    I18n.t('views.lojas.share', loja: nome)
  end

  def local
    locais[0]
  end

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/api/lojas_controller.rb
class Api::LojasController < Api::ApiController

  acts_as_token_authentication_handler_for Usuario, only: [:mine, :create, :update, :upload]

  impressionist actions: [:index]

  # GET /api/lojas
  def index
    lojas = Loja.find_like_name(params['nome'])
    lojas = lojas.find_by_estado(params['estado'])
    lojas = lojas.find_by_esporte_categoria(params['esporte'])

    render_json_resource lojas
  end

  # GET /api/lojas/:uuid
  def show
    loja = Loja.find_by_uuid!(params[:uuid])
    impressionist(loja)

    render_json_success nil, 200
  end

  # GET /api/lojas/mine
  def mine
    lojas = Loja.where(responsavel_id: current_usuario.id)

    render_json_resource lojas
  end

  # POST /api/lojas(.:format)
  def create
    loja = build_loja
    loja.responsavel = current_usuario

    if loja.save
      render_json_success loja, 200
    else
      render_json_error loja.errors, 500
    end
  end

  # PATCH/PUT /api/lojas/:uuid
  def update
    loja = Loja.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless loja.nil?
      loja = build_loja(loja)
      if loja.save
        render_json_success loja, 200
      else
        render_json_error loja.errors, 500
      end
    else
      render_json_error 'Loja not found', 404
    end
  end

  # POST /api/lojas/:uuid/upload
  def upload
    loja = Loja.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless loja.nil?
      if loja.update_attribute(:logo, params[:logo])
        render_json_success loja, 200
      else
        render_json_error loja.errors, 500
      end
    else
      render_json_error 'Loja not found', 404
    end
  end

  private

  def build_loja(loja = nil)
    # get the permitted parameters
    loja_attributes = params.permit(:nome, :descricao, :telefone, :email, :website,
      :facebook, :responsavel_uuid, :uuid,
      esportes: [:id],
      horario: [:inicio, :fim, :seg, :ter, :qua, :qui, :sex, :sab, :dom, :detalhes],
      locais: [:latitude, :longitude, :logradouro, :numero, :complemento, :bairro,
        :cidade, :estado, :cep, :pais]
      )

    # extract nested objects
    responsavel_uuid = loja_attributes.delete("responsavel_uuid")
    esporte_attributes = loja_attributes.delete("esportes")
    horario_attributes = loja_attributes.delete("horario")
    locais_attributes = loja_attributes.delete("locais")

    # create a new object or update if it exists
    if loja.nil?
      loja = Loja.new(loja_attributes)
    else
      loja.assign_attributes(loja_attributes)
    end
    loja.esporte_ids = esporte_attributes.map{|e| e["id"]}
    loja.horario = Horario.new(horario_attributes)
    loja.locais = locais_attributes.map{|l| Local.new(l)}
    return loja
  end

end

app/controllers/cadastros/lojas_controller.rb
class Cadastros::LojasController < Cadastros::CadastrosController
  include EsportesUpdate

  # GET /lojas(.:format)
  def index
    if current_usuario.admin?
      @lojas = Loja.all
    else
      @lojas = current_usuario.lojas
    end
    @title = I18n.t('views.cadastros.lojas_title', length: @lojas.length.to_s)
  end

  # GET /lojas/new(.:format)
  def new
    @loja = Loja.new
    @loja.locais.build
    @loja.build_horario

    @title = I18n.t 'views.cadastros.nova_loja_title'
  end

  # POST /lojas(.:format)
  def create
    update_esporte_ids(params[:loja])

    @loja = current_usuario.lojas.build(loja_params)

    if @loja.save
      redirect_to loja_path(@loja)
    else
      render 'new'
    end
  end

  # GET /lojas/:uuid/edit(.:format)
  def edit
    @loja = find_loja_by_uuid

    if @loja.locais.empty?
      @loja.locais.build
    end
    if @loja.horario.blank?
      @loja.build_horario
    end

    @title = I18n.t('views.cadastros.editar_loja_title',
                    loja: @loja.nome).html_safe
  end

  # PATCH/PUT /lojas/:uuid(.:format)
  def update
    @loja = find_loja_by_uuid

    update_esporte_ids(params[:loja])

    if @loja.update(loja_params)
      redirect_to loja_path(@loja)
    else
      render 'edit'
    end
  end

  # DELETE /lojas/:uuid(.:format)
  def destroy
    @loja = find_loja_by_uuid

    @loja.destroy

    redirect_to cadastros_lojas_path
  end

  private

  def find_loja_by_uuid
    if current_usuario.admin?
      Loja.find_by_uuid!(params[:uuid])
    else
      current_usuario.lojas.find_by_uuid!(params[:uuid])
    end
  end

  def loja_params
    params.require(:loja)
          .permit(:nome, :telefone, :email, :website, :facebook, :logo, :fundo,
                  :descricao,
                  esporte_ids: [],
                  locais_attributes: [:id, :latitude, :longitude, :logradouro,
                                      :numero, :complemento, :bairro, :cidade,
                                      :estado, :estado_nome, :cep, :pais],
                  horario_attributes: [:id, :seg, :ter, :qua, :qui, :sex, :sab,
                                       :dom, :inicio, :fim, :detalhes])
  end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  impressionist actions: [:index]

  # GET /lojas(.:format)
  def index
    load_lojas

    @title = I18n.t 'views.lojas.title'

    flash.now[:alert] = I18n.t 'views.lojas.not_found' if @locais.empty?

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @locais.to_json }
    end
  end

  # GET /lojas/:uuid(.:format)
  def show
    load_lojas unless request.xhr?

    @loja = Loja.find_by_uuid!(params[:uuid])

    impressionist(@loja)

    @title = @loja.nome

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @loja.to_json }
    end
  end

  private

  def load_lojas
    @locais = Local.lojas.paginate(page: params[:page], per_page: 9)
    @locais = @locais.lojas_by_estado(params[:estado]) if params[:estado].present?
    @locais = @locais.lojas_by_esporte_categoria(params[:esporte]) if params[:esporte].present?

    @clear = params[:filter] && params[:page].blank? || nil
  end
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/views/lojas/_loja.html.erb
<div itemscope itemtype="http://schema.org/Place">
  <div class="title" itemprop="name">
    <% if dialog %>
      <% if loja.logo.exists? %>
        <%= image_tag loja.logo.url(:small), class: loja.fundo? ? "fundo" : nil, alt: loja.nome, itemprop: "image" %>
      <% else %>
        <%= loja.nome %>
      <% end %>
    <% else %>
      <% if loja.logo.exists? %>
        <%= link_to loja_path(loja), class: "lnk_dialog", url: loja_path(loja), remote: true do %>
          <%= image_tag loja.logo.url(:small), class: loja.fundo? ? "fundo" : nil, alt: loja.nome, itemprop: "image" %>
        <% end %>
      <% else %>
        <%= link_to loja.nome, loja_path(loja), class: "lnk_dialog", url: loja_url(loja), remote: true %>
      <% end %>
    <% end %>
  </div>

  <div class="desc" itemprop="description">
      <%= loja.descricao %>
  </div>

  <div class="local_attr">
    <ul>
      <% if loja.telefone.present? %>
        <li>
          <i class="fa fa-phone"></i>
          <%=  loja.telefone %>
        </li>
      <% end %>
      <% if loja.email.present? %>
        <li>
          <%= mail_to loja.email do %>
            <i class="fa fa-envelope"></i>
            <%=  loja.email %>
          <% end %>
        </li>
      <% end %>
      <% if loja.website.present? %>
        <li>
          <%= link_to url_with_protocol(loja.website), target: '_blank' do %>
            <i class="fa fa-link"></i>
            <%=  loja.website %>
          <% end %>
        </li>
      <% end %>
      <% if loja.facebook.present? %>
        <li>
          <%= link_to url_with_protocol(loja.facebook), target: '_blank' do %>
            <i class="fa fa-facebook-square"></i>
            <%=  loja.facebook %>
          <% end %>
        </li>
      <% end %>
      <% if local.endereco.present? %>
        <li>
          <i class="fa fa-building attr_ico"></i>
          <span class="attr_txt"><%= local.endereco %></span>
        </li>
      <% end %>
      <% if dialog %>
        <li>
            <%= render "layouts/shares", localizavel: loja, picture_url: loja.logo_url %>
        </li>
      <% end %>
    </ul>
  </div>

  <div itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
    <meta itemprop="latitude" content="<%= local.latitude %>" />
    <meta itemprop="longitude" content="<%= local.longitude%>" />
  </div>
</div>

app/views/lojas/_lojas.html.erb
<%= render "locais/maps.html", locais: @locais %>

<div class="content-head">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#"><%= t 'views.lojas.content_head' %></a></li>
        </ul>
        <div class="search_controls">
          <%= form_for lojas_path, html: { id: "form_lojas" } ,remote: true, format: :json do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais/locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

app/views/lojas/index.html.erb
<%= render "lojas.html", locais: @locais %>

<div class="wrap_paginate">
  <%= will_paginate @locais, remote: true, format: :json %>
</div>

app/views/lojas/index.js.erb
<%= render 'locais/locais.js' %>

app/views/lojas/search.js.erb
<%= render 'locais/locais.js' %>

app/views/lojas/show.html.erb
<%= meta_tags(request.original_url,
              full_title(@loja.nome),
              @loja.share_message,
              @loja.logo_url) %>

<%= render "lojas.html", locais: @locais %>

<script type="text/javascript">
  $(document).ready(function() {
    Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
      + '<%= j render "loja.html", loja: @loja, local: @loja.local, dialog: true %>'
      + '</div>', function() { window.location.replace('<%= lojas_url %>'); });
  });
</script>

app/views/lojas/show.js.erb
Utils.updateMetaTags(
  '<%= request.original_url %>',
  '<%= full_title(@loja.nome) %>',
  '<%= @loja.share_message %>',
  '<%= @loja.logo_url %>');

Utils.dynamicNavigation('<%= request.original_fullpath %>', '<%= full_title(@loja.nome) %>');

Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
  + '<%= j render "loja.html", loja: @loja, local: @loja.local, dialog: true %>'
  + '</div>', function() {
      Utils.updateMetaTags("<%= request.base_url %>");
      Utils.dynamicNavigation();
});