config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :usuarios, controllers: {
    registrations: 'usuario/registrations',
    sessions: 'usuario/sessions',
    passwords: 'usuario/passwords',
    omniauth_callbacks: 'usuario/omniauth_callbacks'
  }

  # API
  namespace :api do
    devise_scope :usuario do
      match 'usuarios/sign_in', to: '/usuario/sessions#create', via: [:post]
      match 'usuarios/sign_out', to: '/usuario/sessions#destroy', via: [:delete]
      match 'usuarios/validate_token',
            to: '/usuario/sessions#validate_token',
            via: [:get]
      match 'usuarios', to: '/usuario/registrations#create', via: [:post]
      match 'usuarios', to: '/usuario/registrations#update', via: [:patch, :put]
      match 'usuarios/password', to: '/usuario/passwords#create', via: [:post]
      match 'usuarios/auth/facebook/validate_token',
            to: '/usuario/omniauth_callbacks#validate_facebook_token',
            via: [:get, :post]
      match 'usuarios/auth/google_oauth2/validate_token',
            to: '/usuario/omniauth_callbacks#validate_google_token',
            via: [:get, :post]
    end
    resources :lojas, only: [:index, :show, :create, :update],
                      param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :pistas, only: [:index, :show, :create, :update],
                       param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :eventos, only: [:index, :show, :create, :update],
                        param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :esportes, only: [:index], defaults: { format: 'json' }
  end

  # CADASTRO
  namespace :cadastros do
    resources :lojas, param: :uuid
    resources :eventos, param: :uuid
    resources :pistas, param: :uuid
    resources :campeonatos, param: :uuid do
      post :evento, on: :member, to: 'campeonatos#create_evento'
      scope module: 'campeonatos' do
        resources :participantes, param: :uuid do
          post :allocate, on: :collection
        end
        resources :etapas, param: :uuid do
          post :generate, on: :collection
        end
      end
    end
  end

  # AUTOCOMPLETE
  resources :esportes, only: [] do
    get :autocomplete_esporte_nome, on: :collection
  end
  resources :locais, only: [] do
    get :autocomplete_cidade_nome, on: :collection
  end

  # PESQUISA
  resources :lojas, only: [:index, :show], param: :uuid
  resources :campeonatos, only: [:index, :show], param: :uuid
  resources :eventos, only: [:index, :show], param: :uuid
  resources :pistas, only: [:index, :show], param: :uuid

  resources :contacts, only: [:index, :create]

  match 'index', to: 'home#index', via: [:get]
  match 'contact', to: 'contacts#index', via: [:get]
  match 'about', to: 'home#about', via: [:get]
  match 'cadastros', to: 'home#cadastros', via: [:get]

  # ERRORS
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/pista.rb
class Pista < ApplicationRecord
  belongs_to :responsavel, class_name: 'Usuario'

  has_one :local, as: :localizavel, dependent: :destroy
  accepts_nested_attributes_for :local, allow_destroy: true

  has_one :horario, as: :funcionamento, dependent: :destroy
  accepts_nested_attributes_for :horario, allow_destroy: true

  has_and_belongs_to_many :esportes

  has_attached_file :foto,
                    styles: {
                      small: '340x200>',
                      original: '1024x768>'
                    }

  is_impressionable

  before_create :set_uuid

  def to_param
    uuid
  end

  validates :nome, presence: true, length: { maximum: 50 }
  validates :descricao, presence: true, length: { maximum: 500 }
  validates :website, length: { maximum: 150 }
  validates :facebook, length: { maximum: 150 }
  validates :video, length: { maximum: 150 }
  validates :local, presence: true
  validates_associated :local
  validates :esportes, presence: true
  validates :responsavel, presence: true
  validates_attachment :foto,
                       size: { in: 0..5.megabytes },
                       content_type: { content_type: /^image\/(jpeg|png)$/ }

  scope :find_like_name, ->(nome) {
    where('pistas.nome LIKE ?', "%#{nome}%") if nome.present?
  }

  scope :find_by_estado, ->(estado) {
    joins(:local).where('locais.estado = ?', estado) if estado.present?
  }

  scope :find_by_esporte_categoria, ->(categoria) {
    joins(:esportes).where(esportes: { categoria: categoria })
                    .distinct if categoria.present?
  }

  def foto_url
    foto.url(:original).sub(/\?\d+$/, '') if foto.exists?
  end

  def responsavel_uuid
    responsavel.uuid
  end

  def as_json(options={})
    super(only: [:nome, :descricao, :website, :facebook, :video, :uuid],
          methods: [:foto_url, :responsavel_uuid],
          include: {
            local: { except: [:id, :localizavel_id, :localizavel_type,
                              :created_at, :updated_at] },
            esportes: { except: [:created_at, :updated_at] },
            horario: { except: [:id, :funcionamento_id, :funcionamento_type,
                                :created_at, :updated_at] }
          }
    )
  end

  def share_message
    I18n.t('views.pistas.share', pista: nome)
  end

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/api/pistas_controller.rb
class Api::PistasController < Api::ApiController

  acts_as_token_authentication_handler_for Usuario, only: [:mine, :create, :update, :upload]

  impressionist actions: [:index]

  # GET /api/pistas
  def index
    pistas = Pista.find_like_name(params['nome'])
    pistas = pistas.find_by_estado(params['estado'])
    pistas = pistas.find_by_esporte_categoria(params['esporte'])

    render_json_resource pistas
  end

  # GET /api/pistas/:uuid
  def show
    pista = Pista.find_by_uuid!(params[:uuid])
    impressionist(pista)

    render_json_success nil, 200
  end

  # GET /api/pistas/mine
  def mine
    pistas = Pista.where(responsavel_id: current_usuario.id)

    render_json_resource pistas
  end

  # POST /api/pistas(.:format)
  def create
    pista = build_pista
    pista.responsavel = current_usuario

    if pista.save
      render_json_success pista, 200
    else
      render_json_error pista.errors, 500
    end
  end

  # PATCH/PUT /api/pistas/:uuid
  def update
    pista = Pista.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless pista.nil?
      pista = build_pista(pista)
      if pista.save pista
        render_json_success pista, 200
      else
        render_json_error pista.errors, 500
      end
    else
      render_json_error 'Pista not found', 404
    end
  end

  # POST /api/pistas/:uuid/upload
  def upload
    pista = Pista.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless pista.nil?
      if pista.update_attribute(:foto, params[:foto])
        render_json_success pista, 200
      else
        render_json_error pista.errors, 500
      end
    else
      render_json_error 'Pista not found', 404
    end
  end

  private

  def build_pista(pista = nil)
    # get the permitted parameters
    pista_attributes = params.permit(:nome, :descricao, :website, :facebook, :video,
      :responsavel_uuid, :uuid,
      esportes: [:id],
      horario: [:inicio, :fim, :seg, :ter, :qua, :qui, :sex, :sab, :dom, :detalhes],
      local: [:latitude, :longitude, :logradouro, :numero, :complemento, :bairro,
        :cidade, :estado, :cep, :pais]
      )

    # extract nested objects
    responsavel_uuid = pista_attributes.delete("responsavel_uuid")
    esporte_attributes = pista_attributes.delete("esportes")
    horario_attributes = pista_attributes.delete("horario")
    local_attributes = pista_attributes.delete("local")

    # create a new object or update if it exists
    if pista.nil?
      pista = Pista.new(pista_attributes)
    else
      pista.assign_attributes(pista_attributes)
    end
    pista.esporte_ids = esporte_attributes.map{|e| e["id"]}
    pista.horario = Horario.new(horario_attributes)
    pista.local = Local.new(local_attributes)
    return pista
  end

end

app/controllers/cadastros/pistas_controller.rb
class Cadastros::PistasController < Cadastros::CadastrosController
  include EsportesUpdate

  # GET /pistas(.:format)
  def index
    if current_usuario.admin?
      @pistas = Pista.all
    else
      @pistas = current_usuario.pistas
    end
    @title = I18n.t('views.cadastros.pistas_title',
                    length: @pistas.length.to_s)
  end

  # GET /pistas/new(.:format)
  def new
    @pista = Pista.new
    @pista.build_local
    @pista.build_horario

    @title = I18n.t 'views.cadastros.nova_pista_title'
  end

  # POST /pistas(.:format)
  def create
    update_esporte_ids(params[:loja])

    @pista = current_usuario.pistas.build(pista_params)

    if @pista.save
      redirect_to pista_path(@pista)
    else
      render 'new'
    end
  end

  # GET /pistas/:uuid/edit(.:format)
  def edit
    @pista = find_pista_by_uuid

    if @pista.local.blank?
      @pista.build_local
    end
    if @pista.horario.blank?
      @pista.build_horario
    end

    @title = I18n.t('views.cadastros.editar_pista_title',
                    pista: @pista.nome).html_safe
  end

  # PATCH/PUT /pistas/:uuid(.:format)
  def update
    @pista = find_pista_by_uuid

    update_esporte_ids(params[:loja])

    if @pista.update(pista_params)
      redirect_to pista_path(@pista)
    else
      render 'edit'
    end
  end

  # DELETE /pistas/:uuid(.:format)
  def destroy
    @pista = find_pista_by_uuid

    @pista.destroy

    redirect_to cadastros_pistas_path
  end

  private

  def find_pista_by_uuid
    if current_usuario.admin?
      Pista.find_by_uuid!(params[:uuid])
    else
      current_usuario.pistas.find_by_uuid!(params[:uuid])
    end
  end

  def pista_params
    params.require(:pista)
          .permit(:nome, :descricao, :website, :facebook, :foto, :video,
                  esporte_ids: [],
                  local_attributes: [:id, :latitude, :longitude, :logradouro,
                                     :numero, :complemento, :bairro, :cidade,
                                     :estado, :estado_nome, :cep, :pais],
                  horario_attributes: [:id, :seg, :ter, :qua, :qui, :sex, :sab,
                                       :dom, :inicio, :fim, :detalhes])
  end
end

app/controllers/pista_controller.rb
class PistaController < ApplicationController
  def new
    if usuario_signed_in? && current_user.logista
      @title = 'Os mano pira nas novas pistas!!'
      @pista = Pista.new
       respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @pista }
      end
    else
       render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

  def create
    @pista = Pista.new(params[:rota])

    respond_to do |format|
      if @pista.save
        format.html { redirect_to @pista, notice: 'Pista was successfully created.' }
        format.json { render json: @pista, status: :created, location: @pista }
      else
        format.html { render action: "new" }
        format.json { render json: @pista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rotas/1
  # DELETE /rotas/1.json
  def destroy
    @pista = Pista.find(params[:id])
    @pista.destroy

    respond_to do |format|
      format.html { redirect_to rotas_url }
      format.json { head :no_content }
    end
  end

  def update
     @pista = Pista.find(params[:id])

    respond_to do |format|
      if @pista.update_attributes(params[:pista])
        format.html { redirect_to @pista, notice: 'Pista was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pista.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/pistas_controller.rb
class PistasController < ApplicationController
  impressionist actions: [:index]

  # GET /pistas(.:format)
  def index
    load_pistas

    @title = I18n.t 'views.pistas.title'

    flash.now[:alert] = I18n.t 'views.pistas.not_found' if @locais.empty?

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @locais.to_json }
    end
  end

  # GET /pistas/:uuid(.:format)
  def show
    load_pistas unless request.xhr?

    @pista = Pista.find_by_uuid!(params[:uuid])

    impressionist(@pista)

    @title = @pista.nome

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @pista.to_json }
    end
  end

  private

  def load_pistas
    @locais = Local.pistas.paginate(page: params[:page], per_page: 9)
    @locais = @locais.pistas_by_estado(params[:estado]) if params[:estado].present?
    @locais = @locais.pistas_by_esporte_categoria(params[:esporte]) if params[:esporte].present?

    @clear = params[:filter] && params[:page].blank? || nil
  end
end

app/helpers/pistas_helper.rb
module PistasHelper
end

app/views/pistas/_pista.html.erb
<div itemscope itemtype="http://schema.org/Place">
  <div class="title" itemprop="name">
      <% if dialog %>
        <%= pista.nome %>
      <% else %>
        <%= link_to pista.nome, pista_path(pista), class: "lnk_dialog", url: pista_path(pista), remote: true %>
      <% end %>
  </div>

  <div class="foto">
    <% if pista.foto.exists? %>
      <%= link_to pista.foto.url(:original), class: "fancybox" do %>
        <%= image_tag pista.foto.url(:small), class: pista.fundo? ? "fundo" : nil, alt: pista.nome, itemprop: "image" %>
      <% end %>
    <% end %>
  </div>

  <div class="desc" itemprop="description">
      <%= pista.descricao %>
  </div>

  <div class="local_attr">
    <ul>
      <% if pista.video.present? %>
        <li>
          <% if dialog %>
            <%= link_to url_with_protocol(pista.video), class: 'fancybox-media video_link' do %>
              <i class="fa fa-video-camera"></i>
              <%= pista.video %>
            <% end %>
            <script type="text/javascript">
              $(function() {
                Utils.getVideoThumb("<%= pista.video %>", function(url) {
                  var $img = $("<img />", {"class" : "video_thumb", "src" : url});
                  $(".video_link").html($img);
                });
              });
            </script>
          <% else %>
            <%= link_to url_with_protocol(pista.video), class: 'fancybox-media' do %>
              <i class="fa fa-video-camera"></i>
              <%= pista.video %>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <% if pista.website.present? %>
        <li>
          <%= link_to url_with_protocol(pista.website), target: '_blank' do %>
            <i class="fa fa-link"></i>
            <%=  pista.website %>
          <% end %>
        </li>
      <% end %>
      <% if pista.facebook.present? %>
        <li>
          <%= link_to url_with_protocol(pista.facebook), target: '_blank' do %>
            <i class="fa fa-facebook-square"></i>
            <%=  pista.facebook %>
          <% end %>
        </li>
      <% end %>
      <% if local.endereco.present? %>
        <li>
          <i class="fa fa-building attr_ico"></i>
          <span class="attr_txt"><%= local.endereco %></span>
        </li>
      <% end %>
      <% if dialog %>
        <li>
            <%= render "layouts/shares", localizavel: pista, picture_url: pista.foto_url %>
        </li>
      <% end %>
    </ul>
  </div>

  <div itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
    <meta itemprop="latitude" content="<%= local.latitude %>" />
    <meta itemprop="longitude" content="<%= local.longitude%>" />
  </div>
</div>

app/views/pistas/_pistas.html.erb
<%= render "locais/maps.html", locais: @locais %>

<div class="content-head">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#"><%= t 'views.pistas.content_head' %></a></li>
        </ul>
        <div class="search_controls">
          <%= form_for pistas_path, html: { id: "form_pistas" }, remote: true, format: :json do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais/locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

app/views/pistas/index.html.erb
<%= render "pistas.html", locais: @locais %>

<div class="wrap_paginate">
  <%= will_paginate @locais, remote: true, format: :json %>
</div>

app/views/pistas/index.js.erb
<%= render 'locais/locais.js' %>

app/views/pistas/search.js.erb
<%= render 'locais/locais.js' %>

app/views/pistas/show.html.erb
<%= meta_tags(request.original_url,
              full_title(@pista.nome),
              @pista.share_message,
              @pista.foto_url) %>

<%= render "pistas.html", locais: @locais %>

<script type="text/javascript">
  $(document).ready(function() {
    Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
      + '<%= j render "pista.html", pista: @pista, local: @pista.local, dialog: true %>'
      + '</div>', function() { window.location.replace('<%= pistas_url %>'); } );
  });
</script>

app/views/pistas/show.js.erb
Utils.updateMetaTags(
  '<%= request.original_url %>',
  '<%= full_title(@pista.nome) %>',
  '<%= @pista.share_message %>',
  '<%= @pista.foto_url %>');

Utils.dynamicNavigation('<%= request.original_fullpath %>', '<%= full_title(@pista.nome) %>');

Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
  + '<%= j render "pista.html", pista: @pista, local: @pista.local, dialog: true %>'
  + '</div>', function() {
      Utils.updateMetaTags("<%= request.base_url %>");
      Utils.dynamicNavigation();
});