config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :usuarios, controllers: {
    registrations: 'usuario/registrations',
    sessions: 'usuario/sessions',
    passwords: 'usuario/passwords',
    omniauth_callbacks: 'usuario/omniauth_callbacks'
  }

  # API
  namespace :api do
    devise_scope :usuario do
      match 'usuarios/sign_in', to: '/usuario/sessions#create', via: [:post]
      match 'usuarios/sign_out', to: '/usuario/sessions#destroy', via: [:delete]
      match 'usuarios/validate_token',
            to: '/usuario/sessions#validate_token',
            via: [:get]
      match 'usuarios', to: '/usuario/registrations#create', via: [:post]
      match 'usuarios', to: '/usuario/registrations#update', via: [:patch, :put]
      match 'usuarios/password', to: '/usuario/passwords#create', via: [:post]
      match 'usuarios/auth/facebook/validate_token',
            to: '/usuario/omniauth_callbacks#validate_facebook_token',
            via: [:get, :post]
      match 'usuarios/auth/google_oauth2/validate_token',
            to: '/usuario/omniauth_callbacks#validate_google_token',
            via: [:get, :post]
    end
    resources :lojas, only: [:index, :show, :create, :update],
                      param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :pistas, only: [:index, :show, :create, :update],
                       param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :eventos, only: [:index, :show, :create, :update],
                        param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :esportes, only: [:index], defaults: { format: 'json' }
  end

  # CADASTRO
  namespace :cadastros do
    resources :lojas, param: :uuid
    resources :eventos, param: :uuid
    resources :pistas, param: :uuid
    resources :campeonatos, param: :uuid do
      post :evento, on: :member, to: 'campeonatos#create_evento'
      scope module: 'campeonatos' do
        resources :participantes, param: :uuid do
          post :allocate, on: :collection
        end
        resources :etapas, param: :uuid do
          post :generate, on: :collection
        end
      end
    end
  end

  # AUTOCOMPLETE
  resources :esportes, only: [] do
    get :autocomplete_esporte_nome, on: :collection
  end
  resources :locais, only: [] do
    get :autocomplete_cidade_nome, on: :collection
  end

  # PESQUISA
  resources :lojas, only: [:index, :show], param: :uuid
  resources :campeonatos, only: [:index, :show], param: :uuid
  resources :eventos, only: [:index, :show], param: :uuid
  resources :pistas, only: [:index, :show], param: :uuid

  resources :contacts, only: [:index, :create]

  match 'index', to: 'home#index', via: [:get]
  match 'contact', to: 'contacts#index', via: [:get]
  match 'about', to: 'home#about', via: [:get]
  match 'cadastros', to: 'home#cadastros', via: [:get]

  # ERRORS
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_usuario!, only: [:cadastros]

  def index
    @title = I18n.t 'views.index.title'

    @locais = Local.localizaveis_active

    flash.now[:alert] = I18n.t 'views.index.not_found' if @locais.empty?

    respond_to do |format|
      format.html { @locais }
      format.js { @locais }
      format.json { render json: @locais.to_json }
    end
  end

  def about
    @title = I18n.t 'views.about.title'
  end

  def cadastros
    if current_usuario.admin?
      @title = I18n.t('views.cadastros.title_admin').html_safe
    elsif current_usuario.lojista?
      @title = I18n.t('views.cadastros.title_lojista').html_safe
      if current_usuario.lojas.blank?
        flash.now[:alert] = I18n.t('views.cadastros.alert_lojista').html_safe
      end
    else
      @title = I18n.t('views.cadastros.title_esportista',
                      usuario: current_usuario.first_name).html_safe
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_locais.html.erb
<% locais.each_with_index do |local, i| %>
    <div class="col_1_of_3 span_1_of_3">
      <% if local.loja? %>
        <%= render "local_loja.html", local: local %>
      <% elsif local.pista? %>
        <%= render "local_pista.html", local: local %>
      <% elsif local.evento? %>
        <%= render "local_evento.html", local: local %>
      <% end %>
    </div>
<% end %>

app/views/home/_locais.js.erb
<% if @clear %>
  $("#paginate_itens").empty();
  CablushShowMap.clearLocations();
<% end %>

$("#paginate_itens").append(" <%= j render "locais.html", locais: @locais %> ");
CablushShowMap.loadLocations(<%= locais_to_json @locais %>);

<% if @locais.next_page %>
  $('.wrap_paginate').html('<%= j will_paginate @locais, :remote => true %>');
<% else %>
  <%#*$(window).off('scroll');%>
  $('.wrap_paginate').html('');
<% end %>

app/views/home/about.html.erb
<div class="main">
    <div class="flex-wrap">
        <div class="content-box">
            <p><%= t 'views.about.description' %></p>
        </div>
        <div class="content-box txt-rt">
            <%=image_tag("slide.jpg", height:'500px',width:"500px",alt:"Cablush Longboard Slide") %>
        </div>
    </div>
    <div class="clear"></div>
</div>

app/views/home/blog.html.erb
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
	<title>Cablush | :: Home :: </title>
</head>
<body>

<%=render "layouts/menu" %>

 <div class="map">
 	<%=image_tag("map.jpg")  %>
 	<!-- <div id="map-canvas">
 		
 	</div> -->
 </div>
 <div class="content-head">
 	<div class="wrap">
 		<ul class="events">
			<li class="active"><a href="index.html">A Cablush</a></li>
			
		</ul>
		<div class="content-box-right" style="width:52%">
			<ul class="events">
			<li class="active" ><a href="index.html">Na Web</a></li> 
			</ul>
	</div>
 	   <div class="clear"></div>
 	</div>
 </div>
 <div class="main">
 	<div class="wrap">
	<div class="section group">
				<div class="cont span_2_of_blog">
				      <div class="blog-left">
							<div class="item_published">
								<span>12</span><br>
								Apr
							</div>	
							<div class="item_head">
								<h5 class="item_title"> <a href="single.html"> Lorem ipsum dolor sit amet, consectetuer</a>
								</h5>
							</div>
							<div class="info">
								<dl class="info_dl">
								 	<dd>
										<div class="item-head">
										Posted by <a href="#">Super User</a></div>
									</dd>
									<dd class="comment1">
									   <span class="comment-left">
										  <a href="#">Comments (8)</a>
									   </span>
									</dd>
									<div class="clear"></div>
								</dl>
							</div>
							<a href="single.html"><img src="web/images/b1.jpg"></a>
					        <p class="f-text1">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
							<a href="single.html" class="link">Read More</a>
						</div>
						<div class="blog-left">
							<div class="item_published">
								<span>12</span><br>
								Apr
							</div>	
							<div class="item_head">
								<h5 class="item_title"> <a href="single.html"> Lorem ipsum dolor sit amet, consectetuer</a>
								</h5>
							</div>
							<div class="info">
								<dl class="info_dl">
								 	<dd>
										<div class="item-head">
										Posted by <a href="#">Super User</a></div>
									</dd>
									<dd class="comment1">
									   <span class="comment-left">
										  <a href="#">Comments (8)</a>
									   </span>
									</dd>
									<div class="clear"></div>
								</dl>
							</div>
							<a href="single.html"><img src="web/images/b2.jpg"></a>
					        <p class="f-text1">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
							<a href="single.html" class="link">Read More</a>
						</div>
						<div class="blog-left1">
							<div class="item_published">
								<span>12</span><br>
								Apr
							</div>	
							<div class="item_head">
								<h5 class="item_title"> <a href="single.html"> Lorem ipsum dolor sit amet, consectetuer</a>
								</h5>
							</div>
							<div class="info">
								<dl class="info_dl">
								 	<dd>
										<div class="item-head">
										Posted by <a href="#">Super User</a></div>
									</dd>
									<dd class="comment1">
									   <span class="comment-left">
										  <a href="#">Comments (8)</a>
									   </span>
									</dd>
									<div class="clear"></div>
								</dl>
							</div>
							<a href="single.html"><img src="web/images/b3.jpg"></a>
					        <p class="f-text1">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
							<a href="single.html" class="link">Read More</a>
						</div>
				</div>
				<div class="bsidebar span_1_of_blog">
					<h2 class="head4">Search</h2>
					<div class="search">
						<form>
							<input type="text" value="Search...." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
							<input type="submit" value="">
						</form>
					</div>
					<h2 class="head4">Categories</h2>
			        <ul class="list1">
					    <li><a href="#">consectetuer adipiscing elit</a></li>
			            <li><a href="#">Duis autem vel eum iriure dolo</a></li>
			            <li><a href="#">soluta nobis eleifend option</a></li>
			            <li><a href="#">consectetuer adipiscing elit</a></li>
			            <li><a href="#">Duis autem vel eum iriure dolo</a></li>
			            <li><a href="#">soluta nobis eleifend option</a></li>
		            </ul>	
	       <div class="sap_tabs">	
			<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
			  <ul class="resp-tabs-list">
			  	  <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>Recent</span></li>
				  <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span>Comments</span></li>
				  <li class="resp-tab-item" aria-controls="tab_item-2" role="tab"><span>Popular</span></li>
				  <div class="clear"></div>
			  </ul>				  	 
				<div class="resp-tabs-container">
				      <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
						<div class="facts">
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w2.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w3.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w4.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w5.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>			              
				        </div>
				     </div>	
				     <div class="tab-2 resp-tab-content" aria-labelledby="tab_item-1">
					 	<div class="facts">
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w6.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w7.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w8.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									    <a href="#" class="link">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w9.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									    <a href="#" class="link">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>			              
				        </div>
					</div>				        					 
				    <div class="tab-3 resp-tab-content" aria-labelledby="tab_item-2">
				     	<div class="facts">
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w10.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									    <a href="#" class="link">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w11.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									     <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w12.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									    <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>	
							<ul class="tab-left">
								<span class="tab-img"><img src="web/images/w13.jpg" alt=""/></span>
									<div class="tab-text">
										<p><a href="#">Lorem ipsum dolor sit amet nibh.</a></p>
										<div class="post-meta">
										   <img src="web/images/comment.png" alt=""><a href="#" class="comments"> 3 Comments</a>
										   <span class="author">Author: <a href="#">Lorem</a></span>
										 </div>
									    <a href="#" class="link1">Read More</a>
									</div>
								<div class="clear"></div>
							</ul>			              
				           </div>           	      
				        </div>	
				     </div>	
		        </div>
	        </div>
	        <h2 class="head4">Tags</h2>
	        <ul class="tags">
				<li><a href="#">Events</a></li>
				<li><a href="#">Gallery</a></li>
				<li><a href="#">Videos</a></li>
				<li><a href="#">Albums</a></li>
				<li><a href="#">Solo Artists</a></li>
				<li><a href="#">Audio Post</a></li>
				<li><a href="#">Musical</a></li>
				<li><a href="#">Live</a></li>
				<li><a href="#">Concert</a></li>
			    <li><a href="#">Movie</a></li>
			 </ul>
	     </div>
	   </div>
	   <div class="clear"></div>
	   </div>
<%=render "layouts/footer"%>
</body>
</html>

app/views/home/cadastros.html.erb
<%= render "layouts/content_header" %>

<div class="main">
  <div class="flex-wrap">
    <div class="content-head">
        <ul class="events">
            <li class="active"><a href="index.html"><%= t 'views.index.content_head_1' %></a></li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="content-head order_3">
        <div class="clear"></div>
    </div>

    <div class="content-box">
        <div class="content">
        <p><%= t 'views.cadastros.content' %></p>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/home/eventos.html.erb
<%= render "maps.html", locais: @locais %>

<div class="content-box">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#">Eventos</a></li> 
        </ul>
        <div class="content-box-left">
          <%= form_for home_eventos_path, html: { id: "form_eventos" } ,remote: true  do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

<div class="wrap_paginate">
  <%= will_paginate @locais, :remote => true  %>
</div>

app/views/home/index.html.erb
<%= render "locais/maps.html", locais: @locais %>

<div class="main">
  <div class="flex-wrap">
    <div class="content-head">
        <ul class="events">
            <li class="active"><a href="index.html"><%= t 'views.index.content_head_1' %></a></li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="content-head order_3">
        <ul class="events">
            <li class="active" ><a href="index.html"><%= t 'views.index.content_head_2' %></a></li>
        </ul>
        <div class="clear"></div>
    </div>

    <div class="content-box">
        <div class="content">
            <p><%= t 'views.index.content_1' %></p>
            <br/>
            <p><%= t 'views.index.content_2' %></p>
            <br/>
            <p>
                <a href="https://play.google.com/store/apps/details?id=com.cablush.cablushapp&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1" target="_blank"><img alt="Get it on Google Play" src="https://play.google.com/intl/en_us/badges/images/generic/pt-br-play-badge.png" width="150"/></a>
            <a href="https://geo.itunes.apple.com/ao/app/cablush/id1102506342?mt=8" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/images/badges/en-us/badge_appstore-lrg.svg) no-repeat;width:165px;height:40px;"></a>
            </p>
            <p class="legal-trademark">Android, Google Play and the Google Play logo are trademarks of Google Inc.</p>
            <p class="legal-trademark">Apple and the Apple logo are trademarks of Apple Inc.</p>

        </div>
        <div class="clear"></div>
    </div>
    <div class="content-box order_4">
        <div class="content">
            <a class="twitter-timeline"  href="https://twitter.com/CablushApp" data-widget-id="701774592789114880">Tweets by @CablushApp</a>
            <script>
              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
            </script>
        </div>
        <div class="clear"></div>
    </div>
  </div>
</div>

app/views/home/lojas.html.erb
<%= render "maps.html", locais: @locais %>

<div class="content-box">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#">Lojas</a></li>
        </ul>
        <div class="content-box-left">
          <%= form_for home_lojas_path, html: { id: "form_lojas" } ,remote: true do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

<div class="wrap_paginate">
  <%= will_paginate @locais, :remote => true  %>
</div>

app/views/home/pistas.html.erb
<%= render "maps.html", locais: @locais %>

<div class="content-box">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#">Pistas</a></li> 
        </ul>
        <div class="content-box-left">
          <%= form_for home_pistas_path, html: { id: "form_pistas" } ,remote: true  do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

<div class="wrap_paginate">
  <%= will_paginate @locais, :remote => true  %>
</div>