config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :usuarios, controllers: {
    registrations: 'usuario/registrations',
    sessions: 'usuario/sessions',
    passwords: 'usuario/passwords',
    omniauth_callbacks: 'usuario/omniauth_callbacks'
  }

  # API
  namespace :api do
    devise_scope :usuario do
      match 'usuarios/sign_in', to: '/usuario/sessions#create', via: [:post]
      match 'usuarios/sign_out', to: '/usuario/sessions#destroy', via: [:delete]
      match 'usuarios/validate_token',
            to: '/usuario/sessions#validate_token',
            via: [:get]
      match 'usuarios', to: '/usuario/registrations#create', via: [:post]
      match 'usuarios', to: '/usuario/registrations#update', via: [:patch, :put]
      match 'usuarios/password', to: '/usuario/passwords#create', via: [:post]
      match 'usuarios/auth/facebook/validate_token',
            to: '/usuario/omniauth_callbacks#validate_facebook_token',
            via: [:get, :post]
      match 'usuarios/auth/google_oauth2/validate_token',
            to: '/usuario/omniauth_callbacks#validate_google_token',
            via: [:get, :post]
    end
    resources :lojas, only: [:index, :show, :create, :update],
                      param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :pistas, only: [:index, :show, :create, :update],
                       param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :eventos, only: [:index, :show, :create, :update],
                        param: :uuid, defaults: { format: 'json' } do
      get :mine, on: :collection
      post :upload, on: :member
    end
    resources :esportes, only: [:index], defaults: { format: 'json' }
  end

  # CADASTRO
  namespace :cadastros do
    resources :lojas, param: :uuid
    resources :eventos, param: :uuid
    resources :pistas, param: :uuid
    resources :campeonatos, param: :uuid do
      post :evento, on: :member, to: 'campeonatos#create_evento'
      scope module: 'campeonatos' do
        resources :participantes, param: :uuid do
          post :allocate, on: :collection
        end
        resources :etapas, param: :uuid do
          post :generate, on: :collection
        end
      end
    end
  end

  # AUTOCOMPLETE
  resources :esportes, only: [] do
    get :autocomplete_esporte_nome, on: :collection
  end
  resources :locais, only: [] do
    get :autocomplete_cidade_nome, on: :collection
  end

  # PESQUISA
  resources :lojas, only: [:index, :show], param: :uuid
  resources :campeonatos, only: [:index, :show], param: :uuid
  resources :eventos, only: [:index, :show], param: :uuid
  resources :pistas, only: [:index, :show], param: :uuid

  resources :contacts, only: [:index, :create]

  match 'index', to: 'home#index', via: [:get]
  match 'contact', to: 'contacts#index', via: [:get]
  match 'about', to: 'home#about', via: [:get]
  match 'cadastros', to: 'home#cadastros', via: [:get]

  # ERRORS
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :responsavel, class_name: 'Usuario'

  has_one :local, as: :localizavel, dependent: :destroy
  accepts_nested_attributes_for :local, allow_destroy: true

  has_and_belongs_to_many :esportes

  belongs_to :campeonato, optional: true

  has_attached_file :flyer,
                    styles: {
                      small: '340x200>',
                      original: '800x600>'
                    }

  is_impressionable

  before_create :set_uuid

  def to_param
    uuid
  end

  validates :nome, presence: true, length: { maximum: 50 }
  validates :descricao, presence: true, length: { maximum: 500 }
  validates :data, presence: true
  validates :hora, presence: true
  validates :website, length: { maximum: 150 }
  validates :facebook, length: { maximum: 150 }
  validates :data_fim, presence: true
  validates :local, presence: true
  validates_associated :local
  validates :esportes, presence: true
  validates :responsavel, presence: true
  validates_attachment :flyer,
                       size: { in: 0..5.megabytes },
                       content_type: { content_type: /^image\/(jpeg|png)$/ }

  scope :actives_ordered, -> {
    where('eventos.data_fim >= ?', Date.today).order('data')
  }

  scope :find_like_name, ->(nome) {
    where('eventos.nome LIKE ?', "%#{nome}%") if nome.present?
  }

  scope :find_by_estado, ->(estado) {
    joins(:local).where('locais.estado = ?', estado) if estado.present?
  }

  scope :find_by_esporte_categoria, ->(categoria) {
    joins(:esportes).where(esportes: { categoria: categoria })
                    .distinct if categoria.present?
  }

  #  scope :public, -> { where(public: true) }
  #  scope :sponsored, -> { where(patrocinado: true) }

  def datas
    datas_tmp = data.strftime('%d/%m/%Y')
    datas_tmp = datas_tmp.try_append(data_fim.strftime('%d/%m/%Y'), ' A ')
    datas_tmp
  end

  def horario
    hora.strftime('%H:%M')
  end

  def start_date
    (data.to_s + ' ' + hora.to_s).to_datetime
  end

  def flyer_url
    flyer.url(:original).sub(/\?\d+$/, '') if flyer.exists?
  end

  def responsavel_uuid
    responsavel.uuid
  end

  def as_json(options={})
    super(only: [:nome, :descricao, :data, :hora, :website, :facebook, :uuid,
                 :data_fim],
          methods: [:flyer_url, :responsavel_uuid],
          include: {
            local: { except: [:id, :localizavel_id, :localizavel_type,
                              :created_at, :updated_at] },
            esportes: { except: [:created_at, :updated_at] }
          }
    )
  end

  def share_message
    I18n.t('views.eventos.share', evento: nome)
  end

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/api/eventos_controller.rb
class Api::EventosController < Api::ApiController

  acts_as_token_authentication_handler_for Usuario, only: [:mine, :create, :update, :upload]

  impressionist actions: [:index]

  # GET /api/eventos
  def index
    eventos = Evento.actives_ordered.find_like_name(params['nome'])
    eventos = eventos.find_by_estado(params['estado'])
    eventos = eventos.find_by_esporte_categoria(params['esporte'])

    render_json_resource eventos
  end

  # GET /api/eventos/:uuid
  def show
    evento = Evento.find_by_uuid!(params[:uuid])
    impressionist(evento)

    render_json_success nil, 200
  end

  # GET /api/eventos/mine
  def mine
    eventos = Evento.actives_ordered.where(responsavel_id: current_usuario.id)

    render_json_resource eventos
  end

  # POST /api/eventos(.:format)
  def create
    evento = build_evento
    evento.responsavel = current_usuario

    if evento.save
      render_json_success evento, 200
    else
      render_json_error evento.errors, 500
    end
  end

  # PATCH/PUT /api/eventos/:uuid
  def update
    evento = Evento.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless evento.nil?
      evento = build_evento(evento)
      if evento.save
        render_json_success evento, 200
      else
        render_json_error evento.errors, 500
      end
    else
      render_json_error 'Evento not found', 404
    end
  end

  # POST /api/eventos/:uuid/upload
  def upload
    evento = Evento.find_by_uuid_and_responsavel_id(params[:uuid], current_usuario.id)

    unless evento.nil?
      if evento.update_attribute(:flyer, params[:flyer])
        render_json_success evento, 200
      else
        render_json_error evento.errors, 500
      end
    else
      render_json_error 'Evento not found', 404
    end
  end

  private

  def build_evento(evento = nil)
    # get the permitted parameters
    evento_attributes = params.permit(:nome, :descricao, :data, :hora, :website,
      :facebook, :responsavel_uuid, :uuid, :data_fim,
      esportes: [:id],
      local: [:latitude, :longitude, :logradouro, :numero, :complemento, :bairro,
        :cidade, :estado, :cep, :pais]
    )

    # extract nested objects
    responsavel_uuid = evento_attributes.delete("responsavel_uuid")
    esporte_attributes = evento_attributes.delete("esportes")
    local_attributes = evento_attributes.delete("local")

    # create a new object or update if it exists
    if evento.nil?
      evento = Evento.new(evento_attributes)
    else
      evento.assign_attributes(evento_attributes)
    end
    evento.esporte_ids = esporte_attributes.map{|e| e["id"]}
    evento.local = Local.new(local_attributes)
    return evento
  end

end

app/controllers/cadastros/eventos_controller.rb
class Cadastros::EventosController < Cadastros::CadastrosController
  include EsportesUpdate

  # GET /eventos(.:format)
  def index
    if current_usuario.admin?
      @eventos = Evento.all.order('data DESC')
    else
      @eventos = current_usuario.eventos.order('data DESC')
    end
    @title = I18n.t('views.cadastros.eventos_title',
                    length: @eventos.length.to_s)
  end

  # GET /eventos/new(.:format)
  def new
    @evento = Evento.new
    @evento.build_local

    @title = I18n.t 'views.cadastros.novo_evento_title'
  end

  # POST /eventos(.:format)
  def create
    update_esporte_ids(params[:evento])

    @evento = current_usuario.eventos.build(evento_params)

    if @evento.save
      redirect_to evento_path(@evento)
    else
      render 'new'
    end
  end

  # GET /eventos/:uuid/edit(.:format)
  def edit
    @evento = find_evento_by_uuid

    if @evento.local.blank?
      @evento.build_local
    end

    @title = I18n.t('views.cadastros.editar_evento_title',
                    evento: @evento.nome).html_safe
  end

  # PATCH/PUT /eventos/:uuid(.:format)
  def update
    @evento = find_evento_by_uuid

    update_esporte_ids(params[:evento])

    if @evento.update(evento_params)
      redirect_to evento_path(@evento)
    else
      render 'edit'
    end
  end

  # DELETE /eventos/:uuid(.:format)
  def destroy
    @evento = find_evento_by_uuid

    @evento.destroy

    redirect_to cadastros_eventos_path
  end

  private

  def find_evento_by_uuid
    if current_usuario.admin?
      Evento.find_by_uuid!(params[:uuid])
    else
      current_usuario.eventos.find_by_uuid!(params[:uuid])
    end
  end

  def evento_params
    params.require(:evento)
          .permit(:nome, :descricao, :data, :hora, :data_fim, :website,
                  :facebook, :flyer, :fundo,
                  esporte_ids: [],
                  local_attributes: [:id, :latitude, :longitude, :logradouro,
                                     :numero, :complemento, :bairro, :cidade,
                                     :estado, :estado_nome, :cep, :pais])
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  impressionist actions: [:index]

  # GET /eventos(.:format)
  def index
    load_eventos

    @title = I18n.t 'views.eventos.title'

    flash.now[:alert] = I18n.t 'views.eventos.not_found' if @locais.empty?

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @locais.to_json }
    end
  end

  # GET /eventos/:uuid(.:format)
  def show
    load_eventos unless request.xhr?

    @evento = Evento.find_by_uuid!(params[:uuid])

    impressionist(@evento)

    @title = @evento.nome

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @evento.to_json }
    end
  end

  private

  def load_eventos
    @locais = Local.eventos.paginate(page: params[:page], per_page: 9)
    @locais = @locais.eventos_by_estado(params[:estado]) if params[:estado].present?
    @locais = @locais.eventos_by_esporte_categoria(params[:esporte]) if params[:esporte].present?

    @clear = params[:filter] && params[:page].blank? || nil
  end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_evento.html.erb
<div itemscope itemtype="http://schema.org/Event">
  <div class="title" itemprop="name">
      <% if dialog %>
        <%= evento.nome %>
      <% else %>
        <%= link_to evento.nome, evento_path(evento), class: "lnk_dialog", url: evento_path(evento), remote: true %>
      <% end %>
  </div>

  <div class="flyer">
    <% if evento.flyer.exists? %>
      <%= link_to evento.flyer.url(:original), class: "fancybox" do %>
        <%= image_tag evento.flyer.url(:small), class: evento.fundo? ? "fundo" : nil, alt: evento.nome, itemprop: "image" %>
      <% end %>
    <% end %>
  </div>

  <div class="desc" itemprop="description">
    <%= evento.descricao %>
  </div>

  <meta itemprop="startDate" content="<%= evento.start_date.to_time.iso8601 %>">
  <meta itemprop="endDate" content="<%= evento.data_fim.to_time.iso8601 %>">

  <div class="local_attr">
    <ul>
      <% if evento.datas.present? %>
        <li>
          <i class="fa fa-calendar"></i>
          <%= evento.datas %>
        </li>
      <% end %>
      <% if evento.horario.present? %>
        <li>
          <i class="fa fa-clock-o"></i>
          <%= evento.horario %>
        </li>
      <% end %>
      <% if evento.website.present? %>
        <li>
          <%= link_to url_with_protocol(evento.website), target: '_blank' do %>
            <i class="fa fa-link"></i>
            <%=  evento.website %>
          <% end %>
        </li>
      <% end %>
      <% if evento.facebook.present? %>
        <li>
          <%= link_to url_with_protocol(evento.facebook), target: '_blank' do %>
            <i class="fa fa-facebook-square"></i>
            <%=  evento.facebook %>
          <% end %>
        </li>
      <% end %>
      <% if local.endereco.present? %>
        <li>
          <i class="fa fa-building attr_ico"></i>
          <span class="attr_txt"><%= local.endereco %></span>
        </li>
      <% end %>
      <% if dialog %>
        <li>
            <%= render "layouts/shares", localizavel: evento, picture_url: evento.flyer_url %>
        </li>
      <% end %>
    </ul>
  </div>

  <div itemprop="location" itemscope itemtype="http://schema.org/Place">
    <div itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
      <meta itemprop="latitude" content="<%= local.latitude %>" />
      <meta itemprop="longitude" content="<%= local.longitude%>" />
    </div>
  </div>
</div>

app/views/eventos/_eventos.html.erb
<%= render "locais/maps.html", locais: @locais %>

<div class="content-head">
    <div class="wrap">
        <ul class="events">
            <li class="active"><a href="#"><%= t 'views.eventos.content_head' %></a></li>
        </ul>
        <div class="search_controls">
          <%= form_for eventos_path, html: { id: "form_eventos" }, remote: true, format: :json do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= render "locais/pesquisa_estado_esporte", f: f %>
          <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="wrap row" id="paginate_itens">
      <%= render "locais/locais.html", locais: @locais %>
    </div>
    <div class="clear"></div>
</div>

app/views/eventos/index.html.erb
<%= render "eventos.html", locais: @locais %>

<div class="wrap_paginate">
  <%= will_paginate @locais, remote: true, format: :json %>
</div>

app/views/eventos/index.js.erb
<%= render 'locais/locais.js' %>

app/views/eventos/search.js.erb
<%= render 'locais/locais.js' %>

app/views/eventos/show.html.erb
<%= meta_tags(request.original_url,
              full_title(@evento.nome),
              @evento.share_message,
              @evento.flyer_url) %>

<%= render "eventos.html", locais: @locais %>

<script type="text/javascript">
  $(document).ready(function() {
    Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
      + '<%= j render "evento.html", evento: @evento, local: @evento.local, dialog: true %>'
      + '</div>', function() { window.location.replace('<%= eventos_url %>'); });
  });
</script>

app/views/eventos/show.js.erb
Utils.updateMetaTags(
  '<%= request.original_url %>',
  '<%= full_title(@evento.nome) %>',
  '<%= @evento.share_message %>',
  '<%= @evento.flyer_url %>');

Utils.dynamicNavigation('<%= request.original_fullpath %>', '<%= full_title(@evento.nome) %>');

Utils.openDialog('<div class="col_1_of_3 span_1_of_3">'
  + '<%= j render "evento.html", evento: @evento, local: @evento.local, dialog: true %>'
  + '</div>', function() {
      Utils.updateMetaTags("<%= request.base_url %>");
      Utils.dynamicNavigation();
});